// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsxevghykwugrnxrfznm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzeGV2Z2h5a3d1Z3JueHJmem5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzIwODcsImV4cCI6MjA2NTc0ODA4N30.Sk29mEvuBh-66GLP1Dlr0TC4D061y7_lotZtufLp39M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);